1. Create a null vector of size 10 but the fifth value which is 1.
2. Create a vector with values ranging from 10 to 49.
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 10x10 array with random values and find the minimum and maximum values.
6. Create a random vector of size 30 and find the mean value.


In [2]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
arr=np.zeros(10)

In [4]:
arr[4]=1

In [5]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
#2. Create a vector with values ranging from 10 to 49.
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
arr=np.random.randint(0,9,(3,3))
arr



array([[8, 1, 5],
       [2, 7, 6],
       [0, 2, 5]])

In [20]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
arr=np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

In [24]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
arr=np.random.randint(0,100,(10,10))
arr

array([[33, 41,  4, 90, 43, 97, 50, 83, 43, 54],
       [70, 34, 23, 20, 77, 59, 66, 13, 98, 36],
       [28,  2, 50, 43, 18, 21, 52, 34, 59, 74],
       [ 5, 91, 19, 67, 24, 70,  2, 16, 37, 49],
       [96, 72, 67,  3, 26, 25, 41,  1,  4, 77],
       [72, 62, 96, 62, 62,  2, 23,  8, 69, 96],
       [27, 94, 59, 13, 46, 40, 59, 73, 72, 26],
       [22, 92, 92,  4, 28, 49, 58, 97, 41, 65],
       [94, 77, 24, 14, 93, 44, 91, 87, 10, 54],
       [38, 56,  0, 43, 22, 33, 13, 74, 51, 17]])

In [25]:
arr.min()

0

In [26]:
arr.max()

98

In [31]:
#6. Create a random vector of size 30 and find the mean value.
arr=np.random.random(30)

In [35]:
print(arr)
arr.mean()

[0.87127883 0.11110679 0.45777442 0.361048   0.3368218  0.62435919
 0.99696183 0.31236081 0.55533276 0.60923738 0.46693506 0.22819611
 0.32376085 0.0423704  0.12597293 0.19671822 0.09009172 0.30053508
 0.20974738 0.18370738 0.29418348 0.1749747  0.35253182 0.45510899
 0.38102775 0.95246489 0.0799403  0.85199107 0.97052233 0.88353886]


0.42668670330649966